# Generated by Django 4.1.7 on 2023-03-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('HeartDiseaseorAttack', models.BooleanField()),
                ('HighBP', models.IntegerField()),
                ('HighChol', models.IntegerField()),
                ('CholCheck', models.IntegerField()),
                ('BMI', models.IntegerField()),
                ('Smoker', models.BooleanField()),
                ('Stroke', models.BooleanField()),
                ('Diabetes', models.BooleanField()),
                ('PhysActivity', models.BooleanField()),
                ('Fruits', models.IntegerField()),
                ('Veggies', models.IntegerField()),
                ('HvyAlcoholConsump', models.BooleanField()),
                ('AnyHealthcare', models.BooleanField()),
                ('NoDocbcCost', models.BooleanField()),
                ('GenHlth', models.IntegerField()),
                ('MentHlth', models.IntegerField()),
                ('PhysHlth', models.IntegerField()),
                ('DiffWalk', models.BooleanField()),
                ('Sex', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('Income', models.IntegerField()),
            ],
        ),
    ]
