# Generated by Django 4.1 on 2023-03-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_heartdisease_highbp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heartdisease",
            name="AnyHealthcare",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="CholCheck",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="DiffWalk",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="Fruits",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="HighChol",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="HvyAlcoholConsump",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="NoDocbcCost",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="PhysActivity",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="Smoker",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="Stroke",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="Veggies",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="heartdisease",
            name="result",
            field=models.BooleanField(default=0),
        ),
    ]
